package com.hibernate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
// no need for xml mapping file
@Entity
@Table (name="product_info")
public class Product {
	
	@Id //primary key
	@Column (name="product_id")
	@GeneratedValue(strategy=GenerationType.IDENTITY) //productId is autogenerated no need to provide explicitly
	private int productId;
	
	@Column (name="product_name")
	private String productName;
 
	private int price;
	
	public int getProductId() {
		return productId;
	}
	public void setProductId(int productId) {
		this.productId = productId;
	}
	public String getProductName() {
		return productName;
	}
	public void setProductName(String productName) {
		this.productName = productName;
	}
	public int getPrice() {
		return price;
	}
	public void setPrice(int price) {
		this.price = price;
	}
	
}